[package]
name = "gala"
version = "0.0.0"
description = "Local photo view engine desktop app"
authors = ["Gala"]
edition = "2021"

[lib]
name = "gala_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
walkdir = "2"

[dev-dependencies]
tempfile = "3"
